### PR TITLE
Edit command bug

### LINKED ISSUE #57: Edit Patient Command does not edit patient fields in Appointment Schedule
## to reproduce: 
*(from clean slate, ie. `clear-appt`, `clear-patient`, though not necessary)*

1. `add-patient n/Alice p/99998888 a/NA e/NA@na.com`
2. `add-appt pt/1 dr/Dr. NA at/2021-01-01 dur/1H`
3. `edit-patient 1 n/Bernice`

### 2. did not happen

### LINKED ISSUE #76: edit doctor bug

### PR DESCRIPTION
**Pull request by onnwards**
fixes #68 
# changes made:
### 8. parameterise `UniquePersonList`

after implementation of doctor, added similar implementation to doctor to fix #76

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Person.java [hunk 1]
```diff
@@ -15,21 +16,40 @@
  */
 public abstract class Person {
```
Comment (Jacob-Pang) [inline src/main/java/seedu/address/model/person/Person.java:17]: Should equals check for UUID field?

File: src/main/java/seedu/address/model/appointment/AppointmentContainsKeywordsPredicate.java [hunk 2]
```diff
@@ -33,7 +33,7 @@ public AppointmentContainsKeywordsPredicate(List<String> patientList, List<Strin
     public boolean test(Appointment appointment) {
 
         Predicate<String> isMatchPatient = keyword -> StringUtil.containsWordIgnoreCase(appointment
```
Comment (Jacob-Pang) [inline src/main/java/seedu/address/model/appointment/AppointmentContainsKeywordsPredicate.java]: The predicate cannot check for keywords in the UUID.

File: src/main/java/seedu/address/model/appointment/NonConflictingAppointmentList.java [hunk 3]
```diff
@@ -44,7 +44,7 @@ public boolean contains(Appointment toCheck) {
      * Returns true if the list contains appointments that corresponds to the input patient.
      */
     public boolean hasPatientInSchedule(Patient patient) {
-        return internalList.stream().map(appointment -> appointment.getPatient()).anyMatch(patient::equals);
+        return internalList.stream().anyMatch(pt -> pt.getPatientUuid().equals(patient.getUuid()));
```
Comment (Jacob-Pang) [inline src/main/java/seedu/address/model/appointment/NonConflictingAppointmentList.java]: The variable pt might be misleading here

File: src/main/java/seedu/address/storage/JsonAdaptedAppointment.java [hunk 4]
```diff
@@ -21,7 +21,7 @@
 public class JsonAdaptedAppointment {
     public static final String MISSING_FIELD_MESSAGE_FORMAT = "Appointment's %s field is missing!";
 
-    private final JsonAdaptedPatient patient;
+    private final UUID patient;
```
Comment (Jacob-Pang) [inline src/main/java/seedu/address/storage/JsonAdaptedAppointment.java]: Is this supposed to be String as per JsonAdaptedPerson

**Review by Jacob-Pang — APPROVED** [review]
