### PR TITLE
Issue Fix for V1.4

### LINKED ISSUE #85: find-appt uses n/ for patient name
using `n/` for patient name seems unintuitive as `dr/` is used for doctor name. `pt/` should be used instead.

### LINKED ISSUE #97: [PE-D] find-appt: Different valid date format, produces different results
Problem:
I tried to find an appointment by using "08/05/2021 12:00" and "2021-05-08 12:00", both are which are valid date formats but expressed differently, however they returns different outputs.

Steps to reproduce:
1) Type in "find-appt at/2021-05-08 12:00"
2) Type in "find-appt at/08/05/2021 12:00"
* Make sure the appointment exists in the first place

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: marcusleeeugene/ped#8

### LINKED ISSUE #99: [PE-D] add-appt: Stated command in UG does not work in program
Problem:
Stated command in UG does not work in program

Steps to reproduce:
1) Type in "add-appt pt/3 dr/1 at/NEXT MONDAY dur/1H 30M"

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: marcusleeeugene/ped#10

### LINKED ISSUE #102: [PE-D] find-appt : Providing only phone won't run find-appt
Only putting in phone number will result in invalid command format

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: godjuansan/ped#1

### LINKED ISSUE #124: [PE-D] Adding invalid date (Old dates) are allowed
When inputting an old date, the appt can still be scheduled

Could be an issue or as part of feature that we can add old appt

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: jrvslam/ped#2

### LINKED ISSUE #135: [PE-D] Find-appt example in UG with wrong format
find-appt Besty does not match the find-appt format.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: Hzxin/ped#4

### LINKED ISSUE #145: [PE-D] More detailed description of valid date format
More details could be given for the input format for date and time, which are the highlighted portions in the image.  Having just examples to show the format might not be clear enough. For example one might be confused with what the term "recognisable datetime format" refers to and one might thing that "recognisable datetime format" includes more than just one kind of accepted format.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: clarlzx/ped#8

### PR DESCRIPTION
**Pull request by kwmiw**
## Edits:
- Change prefix in find-appt to respond and search by `PREFIX_PATIENT` for Patient name instead [ Fixes #85 ]
- Update UG for more clarity on acceptable DateTime Formats [ Fixes #145 ]
- Update UG for wrong prefixes in `find-appt` [ Fixes #135 ]
- Update UG for wrong accepted parameters in `find-appt` [ Fixes #102 ]
- Restrict Old Invalid Date and Time Input. User can now only input future dates [ Fixes #124 ] 
- Allow for parsing for next keyword without user-specified time. Example: `at/next monday` is allowed. [ Fixes #99 ]
- Parses `TIMESLOT_START` to LocalDateTime and back to String in `find-appt` to standardise LocalDateTime format for string match search in `AppointmentContainsKeywordPredicate`. User can now search by date, time or both fields. Refer to UG for more info. Added `parseStandardDate` and `parseStandardTime`  methods and `StandardDateFormat` enum just for parsing dates in `TimeslotParser`[ Fixes #97]

### CODE REVIEW

File: src/main/java/seedu/address/model/appointment/AppointmentContainsKeywordsPredicate.java [hunk 1]
```diff
@@ -68,7 +68,7 @@ public boolean test(Appointment appointment) {
 
         return patientList.stream().map(patientNameSplitMapper).anyMatch(isMatchPatientName)
                 || doctorList.stream().anyMatch(isMatchDoctor)
```
Comment (onnwards) [inline src/main/java/seedu/address/model/appointment/AppointmentContainsKeywordsPredicate.java:71]: i think this is a bug, didn't notice in the PR when doctor was changed from string to Doctor

Comment (onnwards) [reply src/main/java/seedu/address/model/appointment/AppointmentContainsKeywordsPredicate.java:71]: can follow the patientList way to do this

File: docs/UserGuide.md [hunk 2]
```diff
@@ -334,24 +335,27 @@ Examples:
 ### Locating appointments by fields : `find-appt`
 Find appointments with details that contain any of the given keywords. <br>
 
-Format: `find-appt [n/PATIENT KEYWORDS] [dr/DOCTOR_KEYWORDS] [d/DATETIME] [p/PHONE] [e/EMAIL] [a/ADDRESS_KEYWORDS] [t/TAG KEYWORDS]`
+Format: `find-appt [pt/PATIENT_NAME] [MORE_KEYWORDS] [dr/DOCTOR_NAME] [MORE_KEYWORDS] [at/TIMESLOT_START] [MORE_KEYWORDS] [t/TAG] [MORE_KEYWORDS]`
```
Comment (onnwards) [inline docs/UserGuide.md:338]: what does this mean?

File: docs/UserGuide.md [hunk 3]
```diff
@@ -334,24 +335,27 @@ Examples:
...
 
-* Where multiple search fields are specified, the search is conditioned on the satisfaction of <strong>all</strong> of the search fields' sub-conditions. e.g. `find n/Alex Edward dr/Jekyll` will match appointments that satisfy both:
+* Where `at/TIMESLOT_START` field is specified, the search is conditioned on the satisfaction of either or both the date and time elements. e.g.:
+  * `find-appt at/05-08-2021 12:00pm` will match appointments that satisfy both the date and time elements.
+  * `find-appt at/12:00pm` will match all appointments that occur at time `12:00pm`
+  * `find-appt at/05-08-2021` will match all appointments that occur on date `05-08-2021`
+* Where multiple search fields are specified, the search is conditioned on the satisfaction of <strong>all</strong> of the search fields' subconditions. e.g. `find-appt n/Alex Edward Bo dr/Jekyll` will match appointments that satisfy both:
   - Jekyll in the assigned doctor's name; and
   - Either Alex or Edward in the patient's name.
```
Comment (onnwards) [inline docs/UserGuide.md:354]: might want to be more specific here? and list 2 or 3 appointments that this will match, ie something like
Apppointment with Patient name: alex and doctor name: Jekyll, or Apppointment with Patient name: edward hyde and doctor name: Jekyll.

to make the formatting more consistent with lines 357/358

File: docs/UserGuide.md [hunk 4]
```diff
@@ -408,6 +412,39 @@ If your changes to the data files makes its format invalid, App-Ointment will di
...
 
+## Acceptable DateTime Formats
+Must be any of:
+### Date:
++ DD-MM-YYYY
++ DD-MM-YY
++ YYYY-MM-DD
++ DD/MM/YYYY
++ DD/MM/YY
++ next DAY [MONDAY, TUESDAY, ...]
```
Comment (onnwards) [inline docs/UserGuide.md:423]: this notation feels abit weird, im not sure if its correct

File: src/main/java/seedu/address/logic/parser/TimeslotParser.java [hunk 5]
```diff
@@ -36,15 +42,15 @@
...
             + "Example:\n" + PREFIX_TIMESLOT_START
-            + "next Wednesday 12:12pm";
-    public static final String MESSAGE_INVALID_TIME_FORMAT = "Input format for time parameters must be: "
-            + "hh:mm (In 24-Hour format) or hh:mmam/pm\n"
-            + "Example:\n"
-            + "15:12 or 03:12pm";
+            + "next Wednesday 12:12pm or next Wednesday";
+    public static final String MESSAGE_INVALID_PAST_DATE_TIME_FORMAT = "Invalid date and time!\n"
+            + "This timeslot has already occurred in the past."
+            + "Please input future dates and times that that have yet to occur as of now.";
```
Comment (onnwards) [inline src/main/java/seedu/address/logic/parser/TimeslotParser.java:53]: missing a space between these 2 lines?

**Review by onnwards — APPROVED** [review]
this PR also fixes #98 right?

otherwise, looks okay, but i didn't test it, do test it yourself before merging

File: src/main/java/seedu/address/model/appointment/AppointmentContainsKeywordsPredicate.java (hunk 1 above)
Comment (onnwards) [reply src/main/java/seedu/address/model/appointment/AppointmentContainsKeywordsPredicate.java:71]: actually, should check whether the patientNameSplitMapper is still valid considering all the new changes to AppointmentContainsKeywordPredicate, or should we revert back to patientList.stream().anyMatch(isMatchDoctor)
